import type { Metadata } from "next";
import { Noto_Sans_Georgian, Geist_Mono , Geist} from "next/font/google";
import "./styles/globals.css";
import Provider from "./components/Provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// Default app font (all pages after Auth): Noto Sans Georgian
const notoSansGeorgian = Noto_Sans_Georgian({
  subsets: ["georgian"],
  weight: ["500", "500", "600", "700"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AVACX",
//   description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSansGeorgian.className} ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Provider>
          <div className="relative flex h-screen flex-col overflow-hidden">
            <div className="flex-1 overflow-auto">
              {children}
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
