package snip

import (
	"regexp"

	"avacx/internal/snip/severity"
)

func vulnerabilityRules() []detectionRule {
	return []detectionRule{
		{
			id:             "OWASP-A02-HARDCODED-CREDS",
			title:          "Hard-coded credential detected",
			description:    "Sensitive secrets should not be embedded in source code. Move them to a secure secrets store or environment variable.",
			category:       CategoryVulnerability,
			subCategory:    "A02:2021 Cryptographic Failures",
			tags:           []string{"secret", "credential", "exposure"},
			cwe:            []string{"CWE-798"},
			owasp:          []string{"A02:2021"},
			references:     []string{"https://owasp.org/Top10/A02_2021-Cryptographic_Failures/"},
			pattern:        regexp.MustCompile(`(?i)(password|passwd|secret|token|api_key|access_key)\s*(:|=)\s*['\"][^'"\n]+['\"]`),
			languages:      nil,
			exploitability: 0.9,
			businessImpact: 1.3,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeUnchanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactLow,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A02-WEAK-HASH",
			title:          "Weak cryptographic hash in use",
			description:    "MD5 or SHA1 hashes are considered weak and should be replaced with SHA256 or a stronger algorithm.",
			category:       CategoryVulnerability,
			subCategory:    "A02:2021 Cryptographic Failures",
			tags:           []string{"crypto", "hash"},
			cwe:            []string{"CWE-327"},
			owasp:          []string{"A02:2021"},
			references:     []string{"https://owasp.org/www-community/vulnerabilities/Use_of_a_Broken_or_Risky_Cryptographic_Algorithm"},
			pattern:        regexp.MustCompile(`(?i)(md5|sha1)\s*\(`),
			languages:      nil,
			exploitability: 0.6,
			businessImpact: 1.2,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeUnchanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactHigh,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A03-SQLI",
			title:          "Potential SQL injection sink",
			description:    "Detected dynamic SQL construction using user-controlled input. Prefer parameterised queries to avoid SQL injection.",
			category:       CategoryVulnerability,
			subCategory:    "A03:2021 Injection",
			tags:           []string{"sql", "injection"},
			cwe:            []string{"CWE-89"},
			owasp:          []string{"A03:2021"},
			references:     []string{"https://owasp.org/Top10/A03_2021-Injection/"},
			pattern:        regexp.MustCompile(`(?i)(select|insert|update|delete)\s+.+(\+|fmt\.Sprintf|printf)`),
			languages:      languagesSet(LanguageJavaScript, LanguageTypeScript, LanguageGo, LanguagePython, LanguagePHP, LanguageJava, LanguageRuby),
			exploitability: 0.95,
			businessImpact: 1.4,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeUnchanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactHigh,
				Availability:       severity.ImpactHigh,
			},
		},
		{
			id:             "OWASP-A03-COMMAND",
			title:          "Command execution using user input",
			description:    "Command execution APIs should validate input and prefer safe wrappers to mitigate command injection.",
			category:       CategoryVulnerability,
			subCategory:    "A03:2021 Injection",
			tags:           []string{"command", "injection"},
			cwe:            []string{"CWE-78"},
			owasp:          []string{"A03:2021"},
			references:     []string{"https://owasp.org/www-community/attacks/Command_Injection"},
			pattern:        regexp.MustCompile(`(?i)(exec|system|popen|Runtime\.getRuntime\(\)\.exec)\s*\(`),
			languages:      languagesSet(LanguageGo, LanguagePython, LanguagePHP, LanguageJava, LanguageRuby, LanguageShell),
			exploitability: 0.9,
			businessImpact: 1.3,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesLow,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeChanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactHigh,
				Availability:       severity.ImpactHigh,
			},
		},
		{
			id:             "OWASP-A01-PATH-TRAVERSAL",
			title:          "Possible path traversal",
			description:    "User-supplied input is concatenated into file system paths. Ensure canonicalisation and allow-listing.",
			category:       CategoryVulnerability,
			subCategory:    "A01:2021 Broken Access Control",
			tags:           []string{"path", "file", "traversal"},
			cwe:            []string{"CWE-22"},
			owasp:          []string{"A01:2021"},
			references:     []string{"https://owasp.org/www-community/attacks/Path_Traversal"},
			pattern:        regexp.MustCompile(`(?i)(\.\./|\.\.)`),
			languages:      languagesSet(LanguageGo, LanguagePython, LanguagePHP, LanguageJavaScript, LanguageJava, LanguageRuby),
			exploitability: 0.8,
			businessImpact: 1.2,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesLow,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeChanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactHigh,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A05-VERBOSE-ERROR",
			title:          "Verbose error exposure",
			description:    "Detailed stack traces or error messages can leak sensitive information. Sanitize errors before returning them to clients.",
			category:       CategoryVulnerability,
			subCategory:    "A05:2021 Security Misconfiguration",
			tags:           []string{"error", "disclosure"},
			cwe:            []string{"CWE-209"},
			owasp:          []string{"A05:2021"},
			references:     []string{"https://owasp.org/www-project-proactive-controls/v3/en/c7-enforce-access-controls"},
			pattern:        regexp.MustCompile(`(?i)(stack trace|traceback|Exception in thread)`),
			languages:      nil,
			exploitability: 0.5,
			businessImpact: 1.1,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeUnchanged,
				Confidentiality:    severity.ImpactLow,
				Integrity:          severity.ImpactLow,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A07-WEAK-PASSWORD-POLICY",
			title:          "Weak password policy detected",
			description:    "Detected lenient password validation. Enforce minimum length and complexity where appropriate.",
			category:       CategoryVulnerability,
			subCategory:    "A07:2021 Identification and Authentication Failures",
			tags:           []string{"password", "policy"},
			cwe:            []string{"CWE-521"},
			owasp:          []string{"A07:2021"},
			references:     []string{"https://owasp.org/Top10/A07_2021-Identification_and_Authentication_Failures/"},
			pattern:        regexp.MustCompile(`(?i)(password).{0,40}(len\s*[<]{1,2}\s*8|minimumLength\s*[:=]\s*[3-7])`),
			languages:      languagesSet(LanguageJavaScript, LanguageTypeScript, LanguageJava, LanguageGo, LanguagePython, LanguagePHP, LanguageRuby),
			exploitability: 0.7,
			businessImpact: 1.2,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionRequired,
				Scope:              severity.ScopeUnchanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactLow,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A05-WILDCARD-CORS",
			title:          "Overly permissive CORS policy",
			description:    "Detected wildcard Access-Control-Allow-Origin. Restrict origins to trusted domains to prevent data exfiltration.",
			category:       CategoryVulnerability,
			subCategory:    "A05:2021 Security Misconfiguration",
			tags:           []string{"cors", "configuration"},
			cwe:            []string{"CWE-942"},
			owasp:          []string{"A05:2021"},
			references:     []string{"https://owasp.org/www-community/attacks/Cross_Site_Request_Forgery#cors-misconfiguration"},
			pattern:        regexp.MustCompile(`(?i)(Access-Control-Allow-Origin)\s*[:=]\s*["']\*["']`),
			languages:      languagesSet(LanguageGo, LanguageJavaScript, LanguageTypeScript, LanguagePython, LanguageJava, LanguagePHP),
			exploitability: 0.6,
			businessImpact: 1.1,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeChanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactLow,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A06-OUTDATED-LIB",
			title:          "Dependency version appears outdated",
			description:    "Detected dependency pinning to a version older than a year. Review for known vulnerabilities.",
			category:       CategoryVulnerability,
			subCategory:    "A06:2021 Vulnerable and Outdated Components",
			tags:           []string{"dependency", "version"},
			cwe:            []string{"CWE-937"},
			owasp:          []string{"A06:2021"},
			references:     []string{"https://owasp.org/Top10/A06_2021-Vulnerable_and_Outdated_Components/"},
			pattern:        regexp.MustCompile(`(?i)(version|require|dependency)[^\n]{0,40}(201[0-9]|2020)`),
			languages:      nil,
			exploitability: 0.3,
			businessImpact: 1.0,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesNone,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeUnchanged,
				Confidentiality:    severity.ImpactLow,
				Integrity:          severity.ImpactLow,
				Availability:       severity.ImpactLow,
			},
		},
		{
			id:             "OWASP-A08-DESERIALIZATION",
			title:          "Insecure deserialization primitive",
			description:    "Ensure deserialization input is validated and consider using allow-lists or safer formats.",
			category:       CategoryVulnerability,
			subCategory:    "A08:2021 Software and Data Integrity Failures",
			tags:           []string{"serialization", "object"},
			cwe:            []string{"CWE-502"},
			owasp:          []string{"A08:2021"},
			references:     []string{"https://owasp.org/www-community/vulnerabilities/Deserialization_of_untrusted_data"},
			pattern:        regexp.MustCompile(`(?i)(pickle\.loads|yaml\.load|gob\.Decode|serialize\()`),
			languages:      languagesSet(LanguagePython, LanguageGo, LanguagePHP, LanguageJava),
			exploitability: 0.7,
			businessImpact: 1.3,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesLow,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeChanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactHigh,
				Availability:       severity.ImpactHigh,
			},
		},
		{
			id:             "OWASP-A10-SSRF",
			title:          "Potential SSRF via unrestricted URL fetch",
			description:    "Validate URLs fetched on behalf of users to prevent SSRF attacks.",
			category:       CategoryVulnerability,
			subCategory:    "A10:2021 Server-Side Request Forgery",
			tags:           []string{"ssrf", "request"},
			cwe:            []string{"CWE-918"},
			owasp:          []string{"A10:2021"},
			references:     []string{"https://owasp.org/Top10/A10_2021-Server-Side_Request_Forgery_(SSRF)/"},
			pattern:        regexp.MustCompile(`(?i)(http\.Get|axios\.get|requests\.get|fetch)\s*\([^\n]*\+`),
			languages:      languagesSet(LanguageGo, LanguageJavaScript, LanguageTypeScript, LanguagePython, LanguageJava),
			exploitability: 0.85,
			businessImpact: 1.2,
			vector: severity.Vector{
				AttackVector:       severity.AttackVectorNetwork,
				AttackComplexity:   severity.AttackComplexityLow,
				PrivilegesRequired: severity.PrivilegesLow,
				UserInteraction:    severity.UserInteractionNone,
				Scope:              severity.ScopeChanged,
				Confidentiality:    severity.ImpactHigh,
				Integrity:          severity.ImpactLow,
				Availability:       severity.ImpactLow,
			},
		},
	}
}
